const binaryExtensionsSet = new Set([
    '.bin',
    '.db',
    '.mdl',
    '.xls',
    '.xlsx',
    '.woff',
    '.woff2',
    '.ttf',
    '.eot',
    '.otf',
    '.pcm',
    '.raw',
    '.wav',
    '.aar',
    '.dat',
    '.exe',
    '.dll',
    '.so',
    '.img',
    '.iso',
    '.vdi',
    '.vmdk',
    '.ova',
    '.msi',
    '.msp',
    '.cab',
    '.jar',
    '.war',
    '.class',
    '.apk',
    '.ipa',
    '.appx',
    '.appxbundle',
    '.msix',
    '.msixbundle',
    '.xap',
    '.deb',
    '.rpm',
    '.dmg',
    '.pkg',
    '.mpkg',
    '.msu',
    '.appref-ms',
    '.wim',
    '.esd',
    '.swm',
    '.vhd',
    '.vhdx',
    '.wimboot',
    '.pup',
    '.chm',
    '.flac',
    '.flv',
    '.gif',
    '.hlp',
    '.icns',
    '.ico',
    '.ics',
    '.iff',
    '.jnlp',
    '.jp2',
    '.jpe',
    '.jpeg',
    '.jpg',
    '.m4a',
    '.m4v',
    '.mid',
    '.midi',
    '.mkv',
    '.mov',
    '.mp3',
    '.mp4',
    '.mp4v',
    '.mpc',
    '.mpe',
    '.mpeg',
    '.mpg',
    '.mpg4',
    '.mpv',
    '.msm',
    '.mst',
    '.mts',
    '.nfo',
    '.nsc',
    '.nzb',
    '.obj',
    '.oga',
    '.ogg',
    '.ogv',
    '.p7b',
    '.p7c',
    '.p7s',
    '.pak',
    '.pbm',
    '.pcx',
    '.pdb',
    '.pdx',
    '.pgm',
    '.pif',
    '.png',
    '.ppm',
    '.prc',
    '.psd',
    '.pub',
    '.raf',
    '.res',
    '.rgb',
    '.rm',
    '.rmvb',
    '.roff',
    '.s3m',
    '.safariextz',
    '.sea',
    '.sit',
    '.sitx',
    '.sldm',
    '.sldx',
    '.smil',
    '.snd',
    '.spc',
    '.sqlite',
    '.sqlitedb',
    '.stl',
    '.swf'
]);

export function isBinaryFile(filename: string): boolean {
    const extension = filename.slice(filename.lastIndexOf('.')).toLowerCase();
    return binaryExtensionsSet.has(extension);
}

export function isLogFile(filename: string): boolean {
    // 首先不带路径的文件名
    const basename = filename.slice(filename.lastIndexOf('/') + 1);

    // 如果是隐藏文件，则直接返回 false
    if (basename.startsWith('.')) {
        return false;
    }

    // 如果是二进制文件，则直接返回 false
    if (isBinaryFile(filename)) {
        return false;
    }

    // 其它情况认为是日志文件
    return true;
}